Algoritmo "ExemploEnquanto"
// exibir todos os números existentes na sequência de 1 a 500
Var
// Seção de Declarações das variáveis 

contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Exibindo os números de 1 até 500")
contador <- 1
enquanto ( contador <= 500 ) faca
         escreval (contador)
         contador <- contador + 1
fimenquanto

Fimalgoritmo