Algoritmo "QUESTAO1"
//Fazer um algoritmo que peça um numero, e ao final, informe se o numero
//digitiado esta a cima de 1000 ou
//abaixo de 1000
Var
// Seção de Declarações das variáveis
num1 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Informe um numero:")
leia(num1)

se(num1 >= 1000) entao
 escreval("O numero informado esta a cima de 1000")
 senao
   escreval("O numero informado esta a baixo de 1000")
 fimse
Fimalgoritmo