Algoritmo "QUESTAO3"
// Desenvolver um programa que apresente
//os quadrados dos números inteiros de 15 a 200.
Var
// Seção de Declarações das variáveis 
contador: inteiro
poten: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 15
enquanto (contador <= 200) faca
         escreval (contador)
         poten <- contador * contador
         escreval (poten)
         contador <- contador + 1
fimenquanto

Fimalgoritmo