Algoritmo "QUESTAO4"
// Desenvolver um programa que apresente o valor da soma dos cem primeiros
//números inteiros (1 + 2 + 3 + 4 + ...
//+ 97 + 98 + 99 + 100)
Var
// Seção de Declarações das variáveis 
contador: inteiro
soma: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 1
soma <- 0
enquanto ( contador <= 100 ) faca
         soma <- soma + contador
         contador <- contador + 1
fimenquanto
escreval (soma)
Fimalgoritmo